### ISSUE TITLE
Utilize Global Website Settings

### ISSUE THREAD

**Issue by onielmartinjr** [onielmartinjr/cen4010#51]
Add the following to the global variable list
-address
-city
-state
-zip
- Display the organization name in all title tags and optionally in the footer
- Display all social media links optionally in the footer
- Populate a **Contact Us** form that will auto-send an e-mail if there is a global e-mail address. (make sure to verify the global e-mail address is still set even after form submission)
- Potentially display a Google Maps Widget when the address is globally populated

**Comment by onielmartinjr** [comment]
I did everything but the last 3 bullet points. The back-end now fully supports all of these items.

Will leave the rest for after we add in the UI.

**Comment by ifeanyi-chukwu** [comment]
the "state" combo list is not pre-populated with the current state in the manage website setting form, so every time a user changes anything in website settings, the state reverts back ti default = "" ...
solution: find option that matches current state and add this to its option tag selected="selected"

**Comment by onielmartinjr** [comment]
@ifeanyi-chukwu 
The state selection is now fixed.

**Comment by onielmartinjr** [comment]
Decided to scrap the about us page.

**Comment by onielmartinjr** [comment]
Finished with the rest!
