### ISSUE TITLE
Manage the age of each pet

### ISSUE THREAD

**Issue by nickJones67** [onielmartinjr/cen4010#61]
The problem: A pet's age is stored in the database instead of their birth date (which is often unknown), so whenever a pet gets older the admin has to manually set the age. 

Possible solutions: Instead of age, have a column for the birth date (or best guess) and auto calculate the age. OR have a chron-job that will incr the ages OR ignore the issue all together and hope that a pet is adopted before the get a year older

**Comment by onielmartinjr** [comment]
@nickJones67 
ehhhh - fuck it. Do you agree?

**Comment by onielmartinjr** [comment]
Gonna close it until you either agree to fuck it or not.
