### ISSUE TITLE
Manage Vaccination

### ISSUE THREAD

**Issue by ifeanyi-chukwu** [onielmartinjr/cen4010#73]
Admin > Manage Vaccinations: the creation of a new vaccine results in a error which basically translates to 'Columns 'Vaccination_name' does not exist in database'.. i checked the database and confirmed this.  One more thing, vaccination names are not showing up as the default value of the text input boxes...
![capture](https://cloud.githubusercontent.com/assets/18235427/14228598/c076f826-f8e7-11e5-9897-8536f6296654.PNG)

**Comment by onielmartinjr** [comment]
Resolved.
